openapi: 3.0.1
info:
  title: Service Life Status API
  description: API para verificar el estado del microservicio
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /api/usecase/life-status:
    get:
      summary: Consultar el estado del servicio
      operationId: checkServiceStatus
      responses:
        '200':
          description: El servicio está activo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LifeStatusResponse'
        '500':
          description: Error interno del servidor

components:
  schemas:
    LifeStatusResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        messageStatus:
          type: string
          example: "Servicio ok"